### ISSUE TITLE
Unable to update the new Visibleland version 

### ISSUE THREAD

**Issue by House-Coulybaly** [ethxnn88/VisibleIsland#4]
![IMG_1387](https://github.com/ethxnn88/VisibleIsland/assets/52885337/1c30b610-c8af-483a-8b0a-9689669d1262)

**Comment by House-Coulybaly** [comment]
On palera1n rootless jailbreak iOS 16.7.4 iPhone 8

**Comment by ethxnn88** [comment]
Sorry, as of now the repo is currently down, I’m trying my best to get it back up as fast as possible. Try again in about 20 minutes.

**Comment by House-Coulybaly** [comment]
Oh alright no problem 🙏🏽

**Comment by ethxnn88** [comment]
Okay, the repo should be back up. Try again and let me know if it still has any issues. Sorry about that!
